# Generated by Django 3.1.5 on 2021-02-20 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('bikeid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('ifdefective', models.BooleanField(default=0)),
                ('ifavailable', models.BooleanField(default=1)),
                ('postcode', models.CharField(max_length=6)),
                ('defective_details', models.CharField(blank=True, max_length=30, null=True)),
                ('ifstation', models.BooleanField()),
                ('postcode_len', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Repwd_Request',
            fields=[
                ('requestid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('requesttime', models.DateTimeField(auto_now_add=True)),
                ('ifdeal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('stationid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('postcode', models.CharField(default='G12 8QQ', max_length=6)),
                ('name', models.CharField(max_length=32)),
                ('postcode_len', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=78)),
                ('postcode', models.CharField(blank=True, max_length=6, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('group', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('managerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.user')),
            ],
        ),
        migrations.CreateModel(
            name='Rentdetails',
            fields=[
                ('rentid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('start_pick', models.DateField(auto_now_add=True)),
                ('end_left', models.DateField(auto_now_add=True, null=True)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('end_time', models.TimeField(auto_now_add=True, null=True)),
                ('start_postion', models.CharField(max_length=6)),
                ('end_position', models.CharField(blank=True, max_length=6, null=True)),
                ('bikeid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app01.bike')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app01.user')),
            ],
        ),
        migrations.AddField(
            model_name='bike',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.station'),
        ),
    ]
