# Generated by Django 3.1.5 on 2021-02-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='postcode',
            field=models.CharField(default='G128QQ', max_length=6),
        ),
    ]
