# Generated by Django 3.1.5 on 2021-02-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20210220_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='imgaeReport',
            field=models.ImageField(default=None, upload_to='media/images'),
        ),
    ]
